#! /usr/bin/env python3
# This script extracts the target URL from Postmark tracking URLs
# $ pmu https://click.pstmrk.it/example.com/1t/AQ/-----w/cS8Kh9hSU8/index.html
# example.com

import sys
from urllib.parse import urlparse, unquote

postmark_url = urlparse(sys.argv[1])
redirect_uricomponent = postmark_url.path.split("/")[2]
redirect_url = "https://" + unquote(redirect_uricomponent)

print("\n", redirect_url)
